### ISSUE TITLE
Timekeeping assigning the same hash when submissions are made in the same block.

### ISSUE THREAD

**Issue by chrisdcosta** [totem-tech/totem-meccano-node#3]
When two or more users submit time records that occur in the same block the users are assigned the same Timehash for their submissions. 

This breaks the a time management UI.

**Comment by JoshOrndorff** [comment]
It's because you're using the random seed directly here https://github.com/totem-tech/totem-meccano-node/blob/master/node/runtime/src/timekeeping.rs#L325

You should hash a tuple containing the random seed along with some other data to prevent collisions. For example including the caller's accountId would would reduce the collisions to happen only when a single user records time more than once in a single block. Including additional parameters like the start_block reduces the problem further.

There is a new recipe about using Randomness that addresses some of this https://substrate.dev/recipes/3-entrees/randomness.html .

**Comment by chrisdcosta** [comment]
@JoshOrndorff thanks. I'm testing a fix now.

**Comment by chrisdcosta** [comment]
Fixed by fadb90c064a4f1fa577191a3d8d72c3992d88da6
